### ISSUE TITLE
Quotes in the release notes string are not escaped 

### ISSUE THREAD

**Issue by rsavin** [guness/bitrise-step-firebase-app-distribution#17] opened 2020-01-24 10:34 UTC
I use firebase app distribution and I got this error: "Error: Too many arguments. Run firebase help appdistribution:distribute for usage instructions"
After some investigation I found out that quotes symbol ("") in the release-notes message isn't escaped and it makes the firebase cli fail if the release notes have quotes.
Example:
```
firebase appdistribution:distribute "/bitrise/deploy/xxx.apk" --app "xxx" --release-notes "Merge pull request from xxxx. Revert "XXXXXX"" --groups "devs"
```
Fails because `"XXXXXX"` surrounded with quotes.

**Comment by nickspragg** [comment] 2020-02-11 05:48
Is there a timeline on when this will be addressed?

**Comment by guness** [comment] 2020-02-13 13:01
not planned, but I will try to have a look at weekend.

**Comment by guness** [comment] 2020-02-16 13:49
@nickspragg can you try `develop` branch by editing `bitrise.yml` file manually and putting following line in appropriate line:

`    - git::https://github.com/guness/bitrise-step-firebase-app-distribution.git@develop:`

**Comment by guness** [comment] 2020-02-19 14:02
PR is open:
https://github.com/bitrise-io/bitrise-steplib/pull/2400

**Comment by guness** [comment] 2020-02-21 08:13
should be fine now on version 0.6.0

**Comment by ArthurCideron** [comment] 2020-02-21 09:27
> should be fine now on version 0.6.0

Hey, nice of you for maintaining this step :).

I'm afraid replacing double quotes with single ones is just shifting the issue somewhere else though.
```I'm a release note``` would be broken because of the ```'``` now.

Have you tried fully escaping the env var  with expansion characters instead ? Like so: ```${release_notes@Q}```

**Comment by guness** [comment] 2020-02-21 12:03
hmm, I have tested against a case like `I am a 'release' note`, but haven't thought about single.
I will check once have a time. 

However I have added file input for this and it should allow any kind of input in the file. It may help a bit.

**Comment by guness** [comment] 2020-02-21 16:57
ok, confirmed what @ArthurCideron 's said. this still is a problem. should be fixed on next release.

**Comment by mikeberlin** [comment] 2020-03-23 15:03
Any update on this? We're running into issues where a single tick (') is causing the "Too many arguments" error.

**Comment by guness** [comment] 2020-03-24 06:56
since we all are home now, I can handle this within the week.

**Comment by guness** [comment] 2020-03-27 21:26
@mikeberlin @ArthurCideron, can you try running your build using develop branch of the step?

**Comment by mikeberlin** [comment] 2020-03-30 20:59
Am I able to do this through my workflow in bitrise? That's the only place I have to test this. I'm not sure I can change where it's pulling the step from.

**Comment by guness** [comment] 2020-03-30 22:10
@mikeberlin you need to edit bitwise.yml file manually and use following line:
`    - git::https://github.com/guness/bitrise-step-firebase-app-distribution.git@develop:`

**Comment by mikeberlin** [comment] 2020-04-02 15:21
@guness 

This is what I have within my yml file. I am still getting the error when attempting to distribute with a tick in my commit messages. Is there something else I need to change?

- firebase-app-distribution:
        inputs:
        - app: "$FIREBASE_APP_ID"
        - groups: "$FIREBASE_DISTRO_GROUP_QA"
        - release_notes: |-
            Author: $GIT_CLONE_COMMIT_AUTHOR_NAME
            Email: $GIT_CLONE_COMMIT_AUTHOR_EMAIL
            Hash: $GIT_CLONE_COMMIT_HASH

            Subject: $GIT_CLONE_COMMIT_MESSAGE_SUBJECT

            Body:
            $GIT_CLONE_COMMIT_MESSAGE_BODY
        - is_debug: 'true'
        - firebase_token: "$FIREBASE_LOGIN_TOKEN"
        - git::https://github.com/guness/bitrise-step-firebase-app-distribution.git@develop:

**Comment by guness** [comment] 2020-04-02 19:51
@mikeberlin 

ah, please try using like this:

```
- git::https://github.com/guness/bitrise-step-firebase-app-distribution.git@develop: 
        inputs:
        - app: "$FIREBASE_APP_ID"
        - groups: "$FIREBASE_DISTRO_GROUP_QA"
        - release_notes: |-
            Author: $GIT_CLONE_COMMIT_AUTHOR_NAME
            Email: $GIT_CLONE_COMMIT_AUTHOR_EMAIL
            Hash: $GIT_CLONE_COMMIT_HASH

            Subject: $GIT_CLONE_COMMIT_MESSAGE_SUBJECT

            Body:
            $GIT_CLONE_COMMIT_MESSAGE_BODY
        - is_debug: 'true'
        - firebase_token: "$FIREBASE_LOGIN_TOKEN"
```

Sorry, should have been more clear.

**Comment by mikeberlin** [comment] 2020-04-03 14:40
@guness That worked, thanks! I was able to use it to deploy via bitrise while using commit messages that contained a tick/apostrophe. Are we able to integrate this so I can use the actual step instead of the direct github link?

Appreciate the help on this!

**Comment by guness** [comment] 2020-04-03 16:16
@mikeberlin I will take out builds and kicked PR for bitwise. After they merge, step will be ready.

**Closed** 2020-04-03 16:17 UTC
Labels: enhancement
